### PR TITLE
window.console -> Polymer.Base

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Merge after https://github.com/Polymer/polymer/issues/3574 gets fixed.

### CODE REVIEW

**Comment by notwaldorf** [comment]
LGTM % the tests come up green (unless they're unrelated. I don't know what's happening in this element)

**Comment by jeffposnick** [comment]
I'm looking into the test failures...

**Comment by jeffposnick** [comment]
The test failures have to do with buggy behavior in the current Firefox stable that is fixed in Firefox Nightly. I'm leaving open a bug to keep track of that and as a reminder to make sure the tests turn green when Firefox rolls out the fixes to stable: https://github.com/PolymerElements/platinum-sw/issues/104

Before merging this PR, is there anything that needs to be done to make sure that a version of the core Polymer library is picked up that has Polymer/polymer#3574 in it? Like bumping the Polymer dependency version in `bower.json`?

**Comment by wibblymat** [comment]
The version in `bower.json` is bumped to `1.5.0` in the PR, which was released 2 days ago. Looks like that should be plenty.

**Comment by jeffposnick** [comment]
👍

**Pull request merged**
